apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: au16zutgj-go 
  janus-idp.io/tekton: au16zutgj-go
  backstage.io/kubernetes-id: au16zutgj-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: au16zutgj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml