apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: au16zutgj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: au16zutgj-go 
  name: au16zutgj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: au16zutgj-go 
